force-app/main/default/objects/Deployment__c/Deployment__c.object-meta.xml
<CustomObject>
    <description>Represents an entire deployment from one environment to another.</description>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DeploymentMetadataItem__c/DeploymentMetadataItem__c.object-meta.xml
<CustomObject>
    <description>A Metadata Item contained within a specific Deployment.</description>
    <label>Deployment Metadata Item</label>
    <nameField>
        <displayFormat>DMI-{00000}</displayFormat>
        <label>Deployment Metadata Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deployment Metadata Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeploymentMetadataItem__c/fields/Deployment__c.field-meta.xml
<CustomField>
    <fullName>Deployment__c</fullName>
    <label>Deployment</label>
    <referenceTo>Deployment__c</referenceTo>
    <relationshipLabel>Deployment Metadata Items</relationshipLabel>
    <relationshipName>Deployment_Metadata_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GeneratePackageAura.cls
public with sharing class GeneratePackageAura {
    
    @AuraEnabled
    public static void attachXmlToDeployment(Id deploymentId) {
        // Even though this is a void method, the Aura response state
        // should still show ERROR if something goes wrong
        
        // TODO: Should we type check for a deployment object ID?
        List<DeploymentMetadataItem__c> deplMetaItems = [
            SELECT Id, Name
            FROM DeploymentMetadataItem__c
            WHERE Deployment__c = :deploymentId
        ];
        
        Blob thaBlob = packageXmlBlobFromMetadataItems(deplMetaItems);
        
    }
    
    public static Blob packageXmlBlobFromMetadataItems(List<DeploymentMetadataItem__c> dmis) {
        // Build envelope
        XmlStreamWriter xsw = new XmlStreamWriter();
        xsw.writeStartDocument('UTF-8', '1.0');
        xsw.writeEndDocument();
        System.debug(xsw.getXmlString());
    }
}